FROM debian:bookworm

RUN apt-get update && apt-get install -y nginx openssl

RUN mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout /etc/nginx/ssl/inception.key \
        -out /etc/nginx/ssl/inception.crt \
        -subj "/C=MA/ST=BenGruir/L=BenGruir/O=42/OU=1337/CN=oukhiar.42.fr"

COPY ./conf/nginx.conf /etc/nginx/sites-enabled/myconfig.conf

ENTRYPOINT  ["nginx", "-g", "daemon off;"]